version: '3.8'

services:
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: gestion_mercados
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./scripts:/docker-entrypoint-initdb.d
        ports:
            - "5434:5432"
volumes:
    postgres-data:
        driver: local
